format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_SAM_C21_Xplained_Pro, bsp: 'true'}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: BSP_CUSTOM_IE0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: ''}
  - type: String
    attributes: {id: BSP_CUSTOM_LAT0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: ''}
  - type: String
    attributes: {id: BSP_CUSTOM_MODE1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_CUSTOM_PE0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: ''}
  - type: String
    attributes: {id: BSP_CUSTOM_TYPE0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: LED_AH}
  - type: String
    attributes: {id: BSP_CUSTOM_TYPE1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: LED_AL}
- type: ElementPosition
  attributes: {x: '560', y: '20', id: BSP_SAM_C21_Xplained_Pro}
